export interface DemoBid {
  id: string;
  title: string;
  agency: string;
  category: string;
  value_min: number;
  value_max: number;
  deadline: string;
  description: string;
  location: string;
  naics_code: string;
}

// Deadlines relative to 2026-03-12
export const demoBids: DemoBid[] = [
  {
    id: "demo-1",
    title: "DoD IT Modernization – Enterprise Cloud Migration",
    agency: "Department of Defense",
    category: "IT",
    value_min: 2000000,
    value_max: 5000000,
    deadline: "2026-03-13", // closing today
    description: "Full modernization of legacy IT systems to cloud-native architecture. Includes migration of 200+ applications, data center consolidation, and ongoing managed services.",
    location: "Arlington, VA",
    naics_code: "541512",
  },
  {
    id: "demo-2",
    title: "City of Oakland Road Resurfacing – District 4",
    agency: "City of Oakland Public Works",
    category: "construction",
    value_min: 800000,
    value_max: 1200000,
    deadline: "2026-03-18", // closing soon (6 days)
    description: "Mill and overlay resurfacing of approximately 12 lane-miles of residential and collector streets. Includes ADA ramp upgrades and pavement markings.",
    location: "Oakland, CA",
    naics_code: "237310",
  },
  {
    id: "demo-3",
    title: "School District Janitorial & Custodial Services",
    agency: "Sacramento Unified School District",
    category: "services",
    value_min: 150000,
    value_max: 150000,
    deadline: "2026-03-15", // closing soon (3 days)
    description: "Annual contract for janitorial and custodial services across 42 school facilities. Includes daily cleaning, deep cleaning, and event support services.",
    location: "Sacramento, CA",
    naics_code: "561720",
  },
  {
    id: "demo-4",
    title: "County Fleet Maintenance & Repair Services",
    agency: "Alameda County Fleet Services",
    category: "services",
    value_min: 200000,
    value_max: 200000,
    deadline: "2026-04-01",
    description: "Preventive maintenance and repair services for a fleet of 340 vehicles including sedans, SUVs, trucks, and heavy equipment.",
    location: "Alameda County, CA",
    naics_code: "811111",
  },
  {
    id: "demo-5",
    title: "State IT Help Desk & End-User Support Services",
    agency: "California Department of Technology",
    category: "IT",
    value_min: 3000000,
    value_max: 8000000,
    deadline: "2026-04-15",
    description: "Multi-year contract for comprehensive IT help desk services supporting 50,000+ state employees. Includes Tier 1-3 support, ITSM platform management, and reporting.",
    location: "Sacramento, CA",
    naics_code: "541519",
  },
  {
    id: "demo-6",
    title: "Federal Cybersecurity Audit & Risk Assessment",
    agency: "U.S. EPA Office of Environmental Information",
    category: "IT",
    value_min: 500000,
    value_max: 500000,
    deadline: "2026-03-19", // closing soon (7 days)
    description: "Independent cybersecurity audit, penetration testing, and risk assessment for EPA information systems per FISMA requirements.",
    location: "Washington, DC",
    naics_code: "541519",
  },
  {
    id: "demo-7",
    title: "Port Authority Terminal Expansion – Phase 2",
    agency: "Port of Long Beach",
    category: "construction",
    value_min: 12000000,
    value_max: 18000000,
    deadline: "2026-05-01",
    description: "Design-build expansion of container terminal including new berth construction, crane foundations, yard paving, and utility infrastructure.",
    location: "Long Beach, CA",
    naics_code: "237990",
  },
  {
    id: "demo-8",
    title: "Transit Authority Vehicle Supplies & Parts",
    agency: "Bay Area Rapid Transit District",
    category: "supplies",
    value_min: 400000,
    value_max: 400000,
    deadline: "2026-04-08",
    description: "Annual blanket purchase order for OEM and aftermarket parts, consumables, and supplies for light rail and bus fleet maintenance operations.",
    location: "Oakland, CA",
    naics_code: "423120",
  },
  {
    id: "demo-9",
    title: "Hospital Linen & Laundry Services",
    agency: "San Francisco Department of Public Health",
    category: "services",
    value_min: 250000,
    value_max: 250000,
    deadline: "2026-03-25",
    description: "Full-service linen rental, laundering, and delivery for two acute care hospital facilities. Includes patient gowns, bed linens, scrubs, and specialty items.",
    location: "San Francisco, CA",
    naics_code: "812332",
  },
  {
    id: "demo-10",
    title: "EPA Environmental Monitoring & Sampling Services",
    agency: "U.S. Environmental Protection Agency",
    category: "services",
    value_min: 750000,
    value_max: 750000,
    deadline: "2026-04-22",
    description: "Field sampling and laboratory analysis services for air quality, water quality, and soil monitoring at 15 designated Superfund sites.",
    location: "Region 9 (Western US)",
    naics_code: "541620",
  },
  {
    id: "demo-11",
    title: "Municipal Website Redesign & Digital Transformation",
    agency: "City of Fresno",
    category: "IT",
    value_min: 120000,
    value_max: 120000,
    deadline: "2026-03-16", // closing soon (4 days)
    description: "Complete redesign and development of City of Fresno public-facing website with CMS integration, accessibility compliance (WCAG 2.1 AA), and online service portals.",
    location: "Fresno, CA",
    naics_code: "541511",
  },
  {
    id: "demo-12",
    title: "Water Authority Pipe Replacement – Zone 7",
    agency: "East Bay Municipal Utility District",
    category: "construction",
    value_min: 5000000,
    value_max: 9000000,
    deadline: "2026-05-15",
    description: "Replacement of aging cast iron water mains with new ductile iron pipe across 8.5 miles of service zone. Includes service lateral reconnections and pavement restoration.",
    location: "East Bay, CA",
    naics_code: "237110",
  },
  {
    id: "demo-13",
    title: "Air Force Base Grounds & Landscaping Services",
    agency: "Travis Air Force Base",
    category: "services",
    value_min: 180000,
    value_max: 180000,
    deadline: "2026-03-28",
    description: "Grounds maintenance, mowing, landscaping, irrigation management, and snow removal for 640-acre military installation.",
    location: "Fairfield, CA",
    naics_code: "561730",
  },
  {
    id: "demo-14",
    title: "VA Medical Center Supply Chain – Disposables",
    agency: "Department of Veterans Affairs",
    category: "supplies",
    value_min: 300000,
    value_max: 300000,
    deadline: "2026-04-05",
    description: "Multi-year contract for medical disposables, PPE, and consumable supplies for outpatient and inpatient departments at Bay Area VAMC.",
    location: "Palo Alto, CA",
    naics_code: "423450",
  },
  {
    id: "demo-13b",
    title: "State DOT Highway Signage Fabrication & Installation",
    agency: "California Department of Transportation",
    category: "supplies",
    value_min: 600000,
    value_max: 600000,
    deadline: "2026-04-18",
    description: "Fabrication, delivery, and installation of regulatory, warning, and guide signs for Interstate 80 corridor improvements. Includes overhead sign structures.",
    location: "Sacramento Region, CA",
    naics_code: "339950",
  },
];
